### ISSUE TITLE
didnt work

### ISSUE THREAD

**Issue by Kapsyloffer** [pvpb0t/NitroLink-generator#1]
0/10

**Comment by pvpb0t** [comment]
> 0/10

bror, gammal kod + nice iq

**Comment by Kapsyloffer** [comment]
Gratis är gott ngl

**Comment by pvpb0t** [comment]
damn du lurkar asså

**Comment by pvpb0t** [comment]
+ du borde se min nästa youtube video (den är ganska bussin) @Kapsyloffer
